version: '3.8'

services:

  web:
    build: ./app
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/usr/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres-server:5432/postgres
    depends_on:
      - postgres-server

  postgres-server:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - fastapi-dbserver-volume:/var/lib/postgresql/data
volumes:
  fastapi-dbserver-volume: