"""init

Revision ID: 71742136e068
Revises: 
Create Date: 2023-05-03 15:52:06.370724

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '71742136e068'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drink_description'), 'drink', ['description'], unique=False)
    op.create_index(op.f('ix_drink_id'), 'drink', ['id'], unique=False)
    op.create_index(op.f('ix_drink_name'), 'drink', ['name'], unique=False)
    op.create_index(op.f('ix_drink_price'), 'drink', ['price'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('customer_phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('customer_email', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('drink_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drink_id'], ['drink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_customer_email'), 'order', ['customer_email'], unique=False)
    op.create_index(op.f('ix_order_customer_name'), 'order', ['customer_name'], unique=False)
    op.create_index(op.f('ix_order_customer_phone'), 'order', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_order_drink_id'), 'order', ['drink_id'], unique=False)
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_index(op.f('ix_order_quantity'), 'order', ['quantity'], unique=False)
    op.create_index(op.f('ix_order_total_price'), 'order', ['total_price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_total_price'), table_name='order')
    op.drop_index(op.f('ix_order_quantity'), table_name='order')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_drink_id'), table_name='order')
    op.drop_index(op.f('ix_order_customer_phone'), table_name='order')
    op.drop_index(op.f('ix_order_customer_name'), table_name='order')
    op.drop_index(op.f('ix_order_customer_email'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_drink_price'), table_name='drink')
    op.drop_index(op.f('ix_drink_name'), table_name='drink')
    op.drop_index(op.f('ix_drink_id'), table_name='drink')
    op.drop_index(op.f('ix_drink_description'), table_name='drink')
    op.drop_table('drink')
    # ### end Alembic commands ###
