# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from sqlmodel import select
import drink_pb2
import drink_pb2_grpc

from sqlalchemy.ext.asyncio import AsyncSession
from services import drink_service
from models.drink import Drink
from database import get_session
from sqlalchemy.orm import sessionmaker

import database


class DrinkServiceGrpcImp(drink_pb2_grpc.DrinkServiceServicer):
    def __init__(self):
        self.session_factory = sessionmaker(
            database.engine, class_=AsyncSession, expire_on_commit=False
        )

    def ListDrinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    async def GetDrink(self, request, context):
        async with self.session_factory() as session:
            result = await session.execute(select(Drink).where(Drink.id == 1))
            drink = result.scalars().first()

        if(drink == None):
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details('Drink not found!')
            raise NotImplementedError('Drink not found!')

        return drink_pb2.Drink(id=drink.id, name=drink.name, description=drink.description, price=drink.price)

    def CreateDrink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDrink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDrink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
