# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drink.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64rink.proto\x12\x0b\x63offee_shop\"E\n\x05\x44rink\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\"\x13\n\x11ListDrinksRequest\"8\n\x12ListDrinksResponse\x12\"\n\x06\x64rinks\x18\x01 \x03(\x0b\x32\x12.coffee_shop.Drink\"\x1d\n\x0fGetDrinkRequest\x12\n\n\x02id\x18\x01 \x01(\t\"F\n\x12\x43reateDrinkRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\"R\n\x12UpdateDrinkRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\" \n\x12\x44\x65leteDrinkRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x15\n\x13\x44\x65leteDrinkResponse2\xff\x02\n\x0c\x44rinkService\x12O\n\nListDrinks\x12\x1e.coffee_shop.ListDrinksRequest\x1a\x1f.coffee_shop.ListDrinksResponse\"\x00\x12>\n\x08GetDrink\x12\x1c.coffee_shop.GetDrinkRequest\x1a\x12.coffee_shop.Drink\"\x00\x12\x44\n\x0b\x43reateDrink\x12\x1f.coffee_shop.CreateDrinkRequest\x1a\x12.coffee_shop.Drink\"\x00\x12\x44\n\x0bUpdateDrink\x12\x1f.coffee_shop.UpdateDrinkRequest\x1a\x12.coffee_shop.Drink\"\x00\x12R\n\x0b\x44\x65leteDrink\x12\x1f.coffee_shop.DeleteDrinkRequest\x1a .coffee_shop.DeleteDrinkResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drink_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DRINK._serialized_start=28
  _DRINK._serialized_end=97
  _LISTDRINKSREQUEST._serialized_start=99
  _LISTDRINKSREQUEST._serialized_end=118
  _LISTDRINKSRESPONSE._serialized_start=120
  _LISTDRINKSRESPONSE._serialized_end=176
  _GETDRINKREQUEST._serialized_start=178
  _GETDRINKREQUEST._serialized_end=207
  _CREATEDRINKREQUEST._serialized_start=209
  _CREATEDRINKREQUEST._serialized_end=279
  _UPDATEDRINKREQUEST._serialized_start=281
  _UPDATEDRINKREQUEST._serialized_end=363
  _DELETEDRINKREQUEST._serialized_start=365
  _DELETEDRINKREQUEST._serialized_end=397
  _DELETEDRINKRESPONSE._serialized_start=399
  _DELETEDRINKRESPONSE._serialized_end=420
  _DRINKSERVICE._serialized_start=423
  _DRINKSERVICE._serialized_end=806
# @@protoc_insertion_point(module_scope)
